# Site settings
title: ZVampirEM's Blog
description: 张恩铭的博客
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: ZVampirEM77
user_description: Stay Hungry, Stay Foolish!
user_title: Software Developer, Cepher
email: zvampirem77@gmail.com
twitter_username: https://twitter.com/Em77Z
github_username:  https://github.com/ZVampirEM77

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
